# (PART) Foundations {-}

# Overview {-#foundations-overview}

```{r, child="_common.Rmd"}
```

**FOUNDATIONS**

In this section the aim is to (1) provide an overview of quantitative research and their applications, by both highlighting visible applications and notable research in various fields. (2) We will under the hood a bit and consider how quantitative research contributes to language research. (3) I will layout the main types of research and situate quantitative text analysis inside these. Some attention will be given to the historical background to understand how theory (generative and usage-based grammar) has frame and to some degree continues to frame language research. (4) We will discuss how the programmatic approaches to language, which are fundamental for quantative text analysis, also provide the opportunity to further science through process documentation and research reproducibility. 

**Learning outcomes**

- DL (1) learn to understand and apply data analysis to derive insight from data
  - ...
- DL (2) learn to understand and apply data knowledge and skills across linguistic and language-related disciplines
- PS (2) learn to produce collaborative and reproducible research using R, RStudio, and GitHub
  - Install R and RStudio and understand how these software work together to facilitate text analysis research.
  - Install Git and open an account in GitHub
- RS (1) identify an applicable area of investigation in a linguistic or language-related field


# Introduction to text analysis

> Science walks forward on two feet, namely theory and experiment...Sometimes it is one foot which is put forward first, sometimes the other, but continuous progress is only made by the use of both.
> ---[Robert A. Millikan](https://www.nobelprize.org/uploads/2018/06/millikan-lecture.pdf) [-@Millikan1923]

```{block, type="rmdkey"}
In this chapter, you will learn:

- where text analysis fits inside general and linguistic quantitative research
- how modern text analysis research is conducted
- fundamental R skills and key steps in producing reproducible research
```

***
In this chapter, you will learn:

- the goals of this textbook
- the reasoning for using the R programming language
- important text conventions employed in this textbook

***



## Quantitative studies

```{block, type="rmdnote"}
Here is a note!
```

## Quantitative language research

### Text analysis

### ...

## Activities {-}

```{block, type="rmdactivity"}
Here is an activity!
```
