# Transform data {#transform-data}

```{r, child="_common.Rmd"}
```

<p style="font-weight:bold; color:red;">INCOMPLETE DRAFT</p>

> ...

```{block, type="rmdkey"}
In this chapter you will learn:

- ...
- ...

```

<!-- COURSE STRUCTURE

TUTORIALS:

- Primers: 
  - Tidy Your Data: https://rstudio.cloud/learn/primers/4
    - Separate and Unite Columns
    - Join datasets

SWIRL:

- ...

WORKED/ RECIPE:

- ...

PROJECT:

- ...

GOALS:

...

-->

```{r transform-data-packages, echo=FALSE}
# Packages

```

Overview...

## Normalize

...

<!-- Consider:

- last.fm lyrics, line-break artifacts
- 


-->

## Recode

...

<!-- Consider:

- ...

-->

## Generate

...

<!-- Consider:

- Syntactic parsing for last.fm music lyrics, phrasal verbs (compound:prt) a la [@Akbary2018], with automated approach
- SOTU Corpus, frequency weighting and scaling for clustering algorithm?
- ...

-->

## Merge

...

<!-- Consider:

- Switchboard Dialog Act Corpus, stand-off meta-data files
- 

-->


## Documentation

...



---

__Notes:__


- Cover Corpus and Document-Term Matrices (DTM)s
